---
title: "GitHub Introduction - BIO 8940"
author: "Roisin Kierstead"
date: "2023-01-24"
output: html_document
---

Following module 3 practical exercise at https://bio8940-uottawa.github.io/class_book/3.2-practical-1.html#


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
usethis::create_github_token()
#this is the generated token: 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
credentials::set_github_pat()
# If prompted for GitHub credentials, enter your PAT in the password field
```

```{r}
#create R project first, then
install.packages("usethis")
library(usethis)
usethis::use_git()

#then restart R

#connect r to github
usethis::git_sitrep()
usethis::use_git_config(
  user.name = "roisinkierstead",
  user.email = "roisinkierstead@gmail.com")


usethis::git_vaccinate() #from help panel: Adds .DS_Store, .Rproj.user, .Rdata, .Rhistory, and .httr-oauth to your global (a.k.a. user-level) .gitignore. This is good practice as it decreases the chance that you will accidentally leak credentials to GitHub.
```

###Issues with token?
```{r}
library(usethis)
gh_token_help()
```


###Practice commiting after new changes
```{r}
cars
hist(cars$speed)
=======


usethis::git_vaccinate() #from help panel: Adds .DS_Store, .Rproj.user, .Rdata, .Rhistory, and .httr-oauth to your global (a.k.a. user-level) .gitignore. This is good practice as it decreases the chance that you will accidentally leak credentials to GitHub.
```

